version: '3.3'

networks:
  default:
    name: nginx-proxy

services:
  nginx:
    user: root
    container_name: nginx
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:80"
      - "4430:443"
    restart: always
    environment:
      DOMAINS: "${DOMAINS:-}"
      HOST_NAMES: "${HOST_NAMES:-}"
      CF_EMAIL: "${CF_EMAIL:-}"
      CF_API_KEY: "${CF_API_KEY:-}"
