version: '3.3'

networks:
  default:
    name: nginx-proxy

volumes:
  certs:

services:
  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
  certbot:
    container_name: certbot
    depends_on:
    - nginx
    build:
      context: ./
      dockerfile: Dockerfile.certbot
    restart: always
    volumes:
      - certs:/certs
    environment:
      HOST_NAMES: "${HOST_NAMES:-}"
      CF_EMAIL: "${CF_EMAIL:-}"
      CF_API_KEY: "${CF_API_KEY:-}"