FROM certbot/dns-cloudflare:latest

RUN mkdir /app

WORKDIR /app

COPY ./certbot/* ./

RUN chmod +x ./generate_certs.sh
RUN chmod +x ./generate_cf_ini.sh
RUN chmod +x ./start.sh

# Copy settings
CMD [ "./start.sh" ]
