version: '3.3'

services:
  nginx:
    user: root
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      DOMAINS: "${DOMAINS:-}"
      HOST_NAMES: "${HOST_NAMES:-}"
      CF_EMAIL: "${CF_EMAIL:-}"
      CF_API_KEY: "${CF_API_KEY:-}"
